---
title: "Taller de R: Estadística y Programación"
date: '11/05/2022'
pagetitle: "Taller 2"
output:
       pdf_document: default
---

<!-- Configuracion de la consola de R -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T , eval = T , warning = T)
```

En este taller se evalúan los temas vistos en las clases 10 a 12 del curso. Lea atentamente las instrucciones del taller.

<!----------------------------------------------------------------------------->
\begin{center} \textcolor{blue}{\subsection{Instrucciones}} \end{center}

- Este taller pesa el **35%** de la nota total del curso y podrá responderlo de manera individual o en grupo de hasta 3 personas. En las primeras líneas del script debe escribir su nombre, código y la versión de R sobre la que está trabajando. Además, al inicio del código debe llamar/instalar las librerías que va a usar en la sesión. Por ejemplo: `pacman`, `rio`, `data.table` y `tidyverse` (a lo menos).

- Debe crear un repositorio en GitHub y después debe crear un proyecto en R conectado al repositorio de GitHub. Este proyecto debe incluir a lo menos tres carpetas: `input` (datos originales), `output` (datos procesados) y `code` (script con la respuesta del taller).

- Si decide trabajar en grupo, recuerde que deben crear un único repositorio de GitHub para todo el grupo. Sin embargo, **Cada integrante** del grupo deberá colgar en Bloque Neón el enlace al repositorio de GitHub antes de las 23:59 horas del **30 de mayo de 2023**.

-   Por favor sea lo más organizado posible y comente paso a paso cada línea de código, pero recuerden **NO** usar ningún acento o carácter especial dentro del código para evitar problemas al abrir los scripts en los diferentes sistemas operativos.

-   No seguir las instrucciones tiene una penalización del **20%** de la nota final.

<!----------------------------------------------------------------------------->
\begin{center} \textcolor{blue}{\section{Problem set 2}} \end{center}

Deberá usar un loop o una función para importar los archivos de la Gran Encuesta Integrada de Hogares que se encuentran en la carpeta `input`. 

## 1.1 Lista de archivos en `input`

Cree un objeto que almacene el vector de nombres de los archivos dentro de la carpeta `input`. Asegúrese de que cada archivo contenga la ruta con la ubicación de cada archivo. 

## 1.2 Importar archivos: `Resto - Características generales (Personas)` 

Use el objeto creado en el punto anterior como insumo de una función que le permita importar los archivos `Resto - Características generales (Personas)` para todos los meses y años. **Hint:** Puede usar la función `import_list()`.

## 1.3 Combinar conjuntos de datos

Combine todos los `data.frame` que importó en el punto anterior en un solo `data.frame` llamado `cg`. **Hint:** Puede usar un loop que sobrescriba todas las variables en formato carácter usando la función `as.character()` y posteriormente puede combinar los usando la función `rbindlist()`.

## 1.4 Describir el conjunto de datos

Presente una tabla de frecuencias de la variable mes. Exporte la tabla en un archivo de formato `.xlsx`.






